const Graph = require('../graph')

test('should Graph', () => {
    let graph = new Graph()
    graph.addVertex("Tokyo")
    expect(graph.adjacencyList["Tokyo"]).toStrictEqual([])
    graph.addVertex("Dallas")
    graph.addVertex("Aspen")
    graph.addEdge("Dallas", "Tokyo")
    expect(graph.adjacencyList["Tokyo"]).toStrictEqual(["Dallas"])
    expect(graph.adjacencyList["Dallas"]).toStrictEqual(["Tokyo"])
    graph.removeEdge("Dallas", "Tokyo")
    expect(graph.adjacencyList["Tokyo"]).toStrictEqual([])
    expect(graph.adjacencyList["Dallas"]).toStrictEqual([])
    graph.addVertex("Hong Kong")
    graph.addEdge("Hong Kong", "Dallas")
    expect(graph.adjacencyList["Dallas"]).toStrictEqual(["Hong Kong"])
    graph.removeVertex("Hong Kong")
    expect(graph.adjacencyList["Hong Kong"]).toBe(undefined)
    expect(graph.adjacencyList["Dallas"]).toStrictEqual([])
})
